import pytest
import pandas as pd
from src.load_data import load_weather_data

def test_load_weather_data(mocker):
    # Intercepts the Pandas method that writes to the database
    mock_to_sql = mocker.patch('pandas.DataFrame.to_sql')
    
    # Intercepts the SQLAlchemy engine creation to avoid connecting to any database
    mocker.patch('src.load_data.create_engine') 
    
    mock_df = pd.DataFrame({'city_name': ['Sao Paulo'], 'temperature': [25]})
    table_name = 'sp_weather'
    
    # Execution
    load_weather_data(table_name, mock_df)
    
    # Assertion
    mock_to_sql.assert_called_once_with(
        name=table_name,
        con=mocker.ANY, # Accepts any connection object generated by SQLAlchemy
        if_exists='append',
        index=False
    )